language: generic

services:
    - docker

env:
  global:
    - DOCKER_IMAGE_NAME=naturalis/top-api

script:
  - docker build -t $DOCKER_IMAGE_NAME:latest ./

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_IMAGE_NAME:latest
  - if [ -n "$TRAVIS_TAG" ];
    then docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$TRAVIS_TAG && docker push $DOCKER_IMAGE_NAME:$TRAVIS_TAG;
    fi
  - docker logout
